### ISSUE TITLE
 navigation.navigate Method is triggered twice after logout.

### ISSUE THREAD

**Issue by mafiusu** [spencercarli/react-navigation-auth-flow#4]
Hey I've tried the tutorial on https://medium.com/the-react-native-log/building-an-authentication-flow-with-react-navigation-fb5de2203b5c and I'have following problem in my app. 

Here is my use-case:

1. User is saving the token etc. using  `onSignIn().then(() => navigation.navigate("SignedIn"));` from a StackNavigator (SignedOut). 

2. User is logged in and wants to log out using 
`onSignOut().then(() => navigation.navigate("SignedOut"))`

3. Redux Persist (Cache) will be cleared. 

4. Now the user wants to login again. The **navigation.navigate ('someView') method** from a **async fetch success** method is **triggered 2 times**. This results that my view navigates 2 times. If I now log out and wants to log in it happens more than that.

Maybe I should force a reset for the navigation?

**Comment by spencercarli** [comment]
Hey there - React Navigation recently introduced a [`SwitchNavigator`](https://reactnavigation.org/docs/switch-navigator.html) that would likely make all of your auth related routing logic much more simple. I would suggest checking it out.

Should solve the issue you're having.

**Comment by mafiusu** [comment]
@spencercarli great thank you for the tip. You're doing a good work on the react native community.
